"""
Curated Danbooru-style tag pools for FN Random Prompt Generator.
Tags follow https://danbooru.donmai.us/wiki_pages/help:tagging conventions (underscores, English).
Expand or edit this file to tune generations — the full Danbooru corpus is not bundled.
"""

QUALITY_PREFIX = [
    "masterpiece, best quality, newest, absurdres, highly detailed",
    "masterpiece, best quality, very aesthetic, absurdres, detailed eyes, detailed skin",
    "masterpiece, best quality, newest, highres, intricate details, sharp focus",
]

# SFW outfits / states
CLOTHING_SFW = [
    "dress",
    "casual",
    "school uniform",
    "serafuku",
    "kimono",
    "yukata",
    "sundress",
    "sweater",
    "hoodie",
    "tank top",
    "shorts",
    "miniskirt",
    "thighhighs",
    "leggings",
    "sportswear",
    "gym uniform",
    "maid",
    "nurse",
    "office lady",
    "suit",
    "wedding dress",
    "china dress",
    "sailor dress",
    "bikini",
    "one-piece swimsuit",
    "wetsuit",
    "armor",
    "fantasy armor",
    "witch hat, witch dress",
    "cape",
    "coat",
    "scarf",
    "hat",
    "beret",
    "apron",
    "pajamas",
    "yoga pants",
]

# NSFW soft — suggestive clothing / partial nudity / mood (no explicit sex acts)
CLOTHING_NSFW_SOFT = [
    "lingerie",
    "lace lingerie",
    "babydoll",
    "chemise",
    "bustier",
    "fishnets",
    "garter straps",
    "thigh strap",
    "micro bikini",
    "string bikini",
    "underwear only",
    "bra and panties",
    "panties",
    "bra",
    "towel",
    "towel around body",
    "naked towel",
    "nude",
    "partially nude",
    "covered nipples",
    "pasties",
    "bodypaint",
    "see-through",
    "wet clothes",
    "shirt lift",
    "skirt lift",
    "undressing",
    "cleavage",
    "sideboob",
    "bare shoulders",
    "bare legs",
    "barefoot",
    "collarbone",
    "bed sheet",
    "bed sheet only",
]

POSE_ACTION_SFW = [
    "standing",
    "standing on one leg",
    "sitting",
    "sitting on chair",
    "squatting",
    "kneeling",
    "lying",
    "lying on back",
    "lying on stomach",
    "walking",
    "running",
    "stretching",
    "arms up",
    "arms behind head",
    "hand on hip",
    "peace sign",
    "waving",
    "looking at viewer",
    "looking back",
    "profile",
    "from side",
    "from behind",
    "dynamic pose",
    "contrapposto",
    "crossed arms",
    "leaning forward",
    "leaning back",
    "head tilt",
    "hair flip",
    "holding phone",
    "eating",
    "drinking",
    "reading book",
    "sleeping",
    "dancing",
    "jumping",
]

POSE_ACTION_NSFW_SOFT = [
    "arched back",
    "bent over",
    "on bed",
    "on all fours",
    "spread legs",
    "legs together",
    "straddling",
    "sitting on bed",
    "lying on bed",
    "against wall",
    "wet skin",
    "steam",
    "heavy breathing",
    "seductive smile",
    "half-closed eyes",
    "bedroom eyes",
    "lip bite",
    "blush",
    "sweat",
    "teasing",
    "covering breasts",
    "covering crotch",
    "finger to mouth",
    "pulling clothes",
]

EXPRESSION_SFW = [
    "smile",
    "light smile",
    "grin",
    "open mouth",
    "surprised",
    "embarrassed",
    "shy",
    "serious",
    "determined",
    "sleepy",
    "angry",
    "pout",
    "one eye closed",
    "wink",
    "tears",
    "laughing",
]

EXPRESSION_NSFW_SOFT = [
    "blush",
    "embarrassed",
    "nervous smile",
    "seductive smile",
    "half-closed eyes",
    "parted lips",
    "drooling",
    "tears",
    "ahegao",
    "rolling eyes",
]

BACKGROUND_SFW = [
    "simple background",
    "white background",
    "gradient background",
    "blue sky",
    "clouds",
    "sunset",
    "night sky",
    "stars",
    "cityscape",
    "street",
    "rooftop",
    "bedroom",
    "living room",
    "kitchen",
    "classroom",
    "library",
    "cafe",
    "beach",
    "ocean",
    "forest",
    "flower field",
    "park",
    "garden",
    "onsen",
    "poolside",
    "rain",
    "snow",
    "fantasy landscape",
    "castle interior",
    "dungeon",
    "spaceship interior",
    "neon lights",
]

BACKGROUND_NSFW = [
    "bedroom",
    "on bed",
    "bathroom",
    "shower",
    "steam",
    "locker room",
    "hotel room",
    "dim lighting",
    "candles",
    "curtains closed",
    "mirror",
    "simple background",
    "dark background",
]

# Explicit sex-act tags (Danbooru naming). Used only when content_mode = NSFW explicit.
EXPLICIT_SOLO = [
    "masturbation",
    "fingering",
    "spread pussy",
    "dildo",
    "egg vibrator",
    "object insertion",
]

EXPLICIT_PARTNERED_MM = [
    "vaginal",
    "sex",
    "straddling",
    "cowgirl position",
    "reverse cowgirl position",
    "missionary",
    "doggystyle",
    "spooning",
    "standing sex",
    "against wall",
    "leg lock",
    "fellatio",
    "irrumatio",
    "deepthroat",
    "licking penis",
    "paizuri",
    "handjob",
    "cunnilingus",
    "sixty-nine",
    "anal sex",
    "double penetration",
    "creampie",
    "cum",
    "facial",
    "ejaculation",
]

EXPLICIT_YURI = [
    "yuri",
    "cunnilingus",
    "fingering",
    "tribadism",
    "scissoring",
    "kissing",
    "breast sucking",
    "groping",
    "covered in cum",
]

# Pair dynamics when 2girls + explicit
EXPLICIT_YURI_EXTRA = [
    "mutual masturbation",
    "shared dildo",
    "strap-on",
]

FALLBACK_CHARACTER_TAGS = [
    "original",
    "hatsune miku",
    "rem (re:zero)",
    "raiden shogun",
    "yae miko",
    "frieren",
    "makima (chainsaw man)",
    "2b (nier automata)",
    "tifa lockhart",
    "aqua (konosuba)",
    "megumin",
    "marin kitagawa",
    "power (chainsaw man)",
    "nilou (genshin impact)",
    "furina (genshin impact)",
]
